version: "3.9"

services:
  eduflex-api:
    build:
      context: .
      dockerfile: Eduflex/Eduflex/Eduflex/Dockerfile
    container_name: eduflex-api
    ports:
      - "5000:5000"   # Host:Container
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_HOST_PATH=/usr/share/dotnet/dotnet
      # Mongo connection string points to "mongo" service
      - ConnectionStrings__MongoDb=mongodb://mongo:27017/EduflexDB
      # Redis connection string points to "redis" service
      - ConnectionStrings__RedisConnection=redis:6379
    depends_on:
      - mongo
      - redis

  eduflex-angular:
    build:
      context: ./eduflex-Angular
      dockerfile: Dockerfile
    container_name: eduflex-angular
    ports:
      - "4200:4200"
    depends_on:
      - eduflex-api

  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo_data: