version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: eduflex-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
      MONGO_INITDB_DATABASE: EduflexDB
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - eduflex-network

  api:
    build: .
    container_name: eduflex-api
    environment:
      - MONGODB_CONNECTION=mongodb://admin:password123@mongodb:27017/EduflexDB
    ports:
      - "7007:80"
    depends_on:
      - mongodb
    networks:
      - eduflex-network

volumes:
  mongodb_data:

networks:
  eduflex-network:
    driver: bridge